---
title: "index"
output: html_document
---

# 11/22/2020

- Attempting to simplify the database Excel file, I started a [new note for annual report 02](note_annual-reports-02.html).
- Meanwhile, finalized the [first note](note_annual-reports-01.html).

# 11/26/2020

- Finished up the annual report with the exported graphs using a [new note](note_annual-reports-03.html).

# 12/16/2020

Wrap up the notes. I wrote casually here and there, having had some troubles re-collecting them... In the Annual Report notebook 02 I gathered and organized them. In the notebook 03, I made report outputs from the database.

1. Extract the code for data handling into independent R scripts.
2. Format the report notes into a report document.

# 5/17/2022

Checking the survey for missing entries.

It appears that I didn't really update the git database for 2021. Just merged into the master branch and pushed, but files are not sorted out or documented here.


# 5/24/2022

I want to check the new data obtained yesterday, but I don't remember how generic the scripts under /R are. Ideally, I want some scripts to load any of AY19, 20, or 21 with those scripts.

1. Copy some scripts to load the new data in a notebook, test the data.
2. Later, check the scripts for the old data. Format the input data as needed.

By the way, we could not retrieve several instances. A few are bad entries such as using PennWest. Others are due to the system errors during the semester. Some rubrics data turned out to be inaccessible. There was an issue with the rubrics during the semester and they did not record outcomes (e.g., Beth's BUS 499).

# 6/2/2022

Codes from AY2020 are quite messy. I cannot tell right away what to do to reproduce AY19 and AY20 results. However, at least, I documented the process in notebooks. I can trace them carefully to learn about the set of scripts used.

To take advantage of the notebook, I need to have a better organization that I can *keep* using over multiple years. Perhaps I can index by year?

Move all the notebook from 2020 into an archive folder. Because the data source files are not standardized, it is hard to keep consistent procedures. As I process the new data (AY2021), I can re-examine AY19 and AY20 scripts. That said, I want to preserve the codes and their outcomes I had in 2021. Archive all including the output html files to an external folder.


